# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/cachew',
                'doc_host': 'https://suchith720.github.io',
                'git_url': 'https://github.com/suchith720/cachew',
                'lib_path': 'cachew'},
  'syms': { 'cachew.00_cachew-for-wikiseealsotitles': {},
            'cachew.00_cachew-for-wikiseealsotitles-001': {},
            'cachew.00_cachew-for-wikiseealsotitles-002': {},
            'cachew.00_cachew-for-wikiseealsotitles-inference': { 'cachew.00_cachew-for-wikiseealsotitles-inference.Encoder.enrich_query_representation': ( 'cachew-for-wikiseealsotitles.html#encoder.enrich_query_representation',
                                                                                                                                                            'cachew/00_cachew-for-wikiseealsotitles-inference.py'),
                                                                  'cachew.00_cachew-for-wikiseealsotitles-inference.Encoder.forward': ( 'cachew-for-wikiseealsotitles.html#encoder.forward',
                                                                                                                                        'cachew/00_cachew-for-wikiseealsotitles-inference.py'),
                                                                  'cachew.00_cachew-for-wikiseealsotitles-inference.Memory.forward': ( 'cachew-for-wikiseealsotitles.html#memory.forward',
                                                                                                                                       'cachew/00_cachew-for-wikiseealsotitles-inference.py')},
            'cachew.01_cachew-for-wikiseealsotitles-with-meta-loss': {},
            'cachew.02_ngame-benchmarking-with-updated-loss': {},
            'cachew.03_cachew-for-wikiseealsotitles-for-training-memory': {}}}
